### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by jhuesos** [sameoldmadness/g-cli#5]
At this point Windows platform is not supported. It would be great if this nice tool also supports it.

**Comment by jhuesos** [comment]
Follow up #4

**Comment by sameoldmadness** [comment]
Well, it seems to be doable.

Here're some sketches:

* [get branch name](https://gist.github.com/sameoldmadness/2c13cfb950547ca90006#file-get-branch-name)
* [switch between list entries](https://gist.github.com/sameoldmadness/2c13cfb950547ca90006#file-select-menu-entries)

Usefull resources:

* [DOS Batch - Function Tutorial](http://www.dostips.com/DtTutoFunctions.php)
* [DOS Batch - Functions](http://www.dostips.com/DtCodeCmdLib.php)
* [Arrays, linked lists and other data structures in cmd.exe (batch) script](http://stackoverflow.com/questions/10166386/arrays-linked-lists-and-other-data-structures-in-cmd-exe-batch-script)

Help is greatly appreciated : )

**Comment by sameoldmadness** [comment]
Closed by #6
